name: Coding Standard

on:
    pull_request: null

jobs:
    coding_standard:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress --ansi

            -   run: vendor/bin/ecs check-markdown README.md --ansi