on:
  check_suite:
    types: [completed]
name: Ci status
jobs:
  ci-status-update:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v2
        if: contains(['success', 'failure', 'cancelled'], github.event.conclusion)
        with:
          status: ${{ github.event.conclusion }}
          icon_emoji: ':octocat:'
          channel: '#ci'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
